### ISSUE TITLE
Uncompleted merge

### ISSUE THREAD

**Issue by dhalbert** [sonydevworld/spresense-micropython#1]
There appears to be an uncompleted merge in
https://github.com/sonydevworld/spresense-exported-sdk/blob/circuitpython/nuttx/scripts/Make.defs

i found this by accident while looking for some uncompleted merges of my own in a local circuitpython clone.

This commit is currently used by the spresense sdk submodule in https://github.com/adafruit/circuitpython.

**Comment by kamtom480** [comment]
@dhalbert Thank you for finding this. I just fixed it and created the PR: https://github.com/adafruit/circuitpython/pull/5069

By the way, I also updated the Spresense SDK to 2.2.0.
